layout_spectrum: 0
typography_spectrum: 0.2658432
color:
  saturation: 0.8426423
  lightness: 1
  brandStrength: 0
  rhythmicContrast: 0.5590762
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: MiPrimeraPágina
